# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

title: "SPARC: Journal Negotiation Community of Practice"
sass:
    style: compressed
exclude: ["README.md"] # files to exclude
markdown: kramdown

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: "SPARC: Journal Negotiation Community of Practice"

description: "The SPARC Journal Negotiation Community of Practice (CoP) is a community-led effort to assist libraries in the development of a more equitable journal negotiations landscape."
author:
  name: Scholarly Publishing and Academic Resources Coalition
  email: nick@sparcopen.org
  github: sparcopen
  twitter: sparc_na
  facebook: sparcopen

BASE_PATH: https://negotiations.sparcopen.org
url: https://negotiations.sparcopen.org # keep this for sitemap
permalink: pretty
plugins:
  - jekyll-sitemap

collections:
  working-groups:
    relative_directory: _working-groups
    output: true
  topics:
    relative_directory: _topics
    output: true
  articles:
    relative_directory: _articles
    output: true
  authors:
    relative_directory: _authors
    output: false
  blog:
    relative_directory: _blog
    output: true
