# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

title: "SPARC: Community Owned Infrastructure"
sass:
    style: compressed
exclude: ["README.md"] # files to exclude
markdown: kramdown

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: "SPARC: Community Owned Infrastructure"

description: "Data and data analytics are spreading fast at higher education institutions, and the academic community is at a critical juncture."
author:
  name: Scholarly Publishing and Academic Resources Coalition
  email: Joe@sparcopen.org
  github: sparcopen
  twitter: sparc_na
  facebook: sparcopen

BASE_PATH: https://negotiations.sparcopen.org
url: https://negotiations.sparcopen.org # keep this for sitemap
plugins:
  - jekyll-sitemap

collections:
  campus-partnerships-planning:
    relative_directory: _campus-partnerships-planning
    output: true
  data-analysis:
    relative_directory: _data-analysis
    output: true
  journal-cancellation-impact:
    relative_directory: _journal-cancellation-impact
    output: true
  reinvestments:
    relative_directory: _reinvestments
    output: true
  topics:
    relative_directory: _topics
    output: true
  authors:
    relative_directory: _authors
    output: false
  blog:
    relative_directory: _blog
    output: true
