# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

title: "SPARC: Community Owned Infrastructure"
sass:
    style: compressed
exclude: ["README.md"] # files to exclude
markdown: kramdown

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: "SPARC: Community Owned Infrastructure"

description: "Data and data analytics are spreading fast at higher education institutions, and the academic community is at a critical juncture."
author:
  name: Scholarly Publishing and Academic Resources Coalition
  email: Joe@sparcopen.org
  github: sparcopen
  twitter: sparc_na
  facebook: sparcopen

BASE_PATH: http://127.0.0.1:4000
# LIVE: https://infrastructure.sparcopen.org/ NETFLY https://upbeat-swirles-009f3e.netlify.app LOCAL: http://127.0.0.1:4000
url: https://infrastructure.sparcopen.org # for sitemap. Doesn't need to change on live / dev.
plugins:
  - jekyll-sitemap

collections:
  campus_partnerships_planning:
    output: true
  data_analysis:
    output: true
  journal_cancellation_impact:
    output: true
  reinvestments:
    output: true
  members:
    output: true
  topics:
    output: true
  reports:
    output: true
