backend:
  name: git-gateway
  repo: sssoz/negotiations
  branch: master
media_folder: 'media/uploads'
collections:
  - name: 'campus-partnerships-planning'
    label: 'Campus Partnerships & Planning post'
    folder: '_campus_partnerships_planning/'
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "with-sidebar"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publishing Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
