backend:
  name: git-gateway
  branch: master
  name: github
  repo: sparcopen/negotiations
media_folder: "media/uploads"
collections:
  - name: "pages"
    label: "Landing pages"
    files:
      - label: "About"
        name: "about"
        file: "about.md"
        fields:
          - { label: "Title", name: "title", widget: "hidden", default: "about" }
          - { label: "Layout", name: "layout", widget: "hidden", default: "about" }
      - label: "Campus Partnerships Planning"
        name: "campus-partnerships-planning"
        file: "campus-partnerships-planning.md"
        fields:
          - { label: "Title", name: "title", widget: "hidden", default: "Data Analysis"}
          - { label: "Layout", name: "layout", widget: "hidden", default: "thread" }
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "Data Analysis"
        name: "data-analysis"
        file: "data-analysis.md"
        fields:
          - { label: "Title", name: "title", widget: "hidden", default: "Data Analysis"}
          - { label: "Layout", name: "layout", widget: "hidden", default: "thread" }
          - {label: "Body", name: "body", widget: "markdown"}
  - name: "authors"
    label: "Authors"
    folder: "_authors/"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Short Name", name: "author_id", widget: "string" }
      - { label: "Display Name", name: "display_name", widget: "string" }
      - { label: "Contact email", name: "email", widget: "string" }
      - { label: "Link to bio", name: "link_bio", widget: "string" }
      - { label: "Bio", name: "bio", widget: "text" }
  - name: "topics"
    label: "Topics"
    folder: "_topics/"
    widget: "list"
    allow_add: true
    label_singular: "Add a new topic"
    add_to_top: true
    create: true
    editor:
      preview: false
    fields:
      - { label: "Topic (short name)", name: "topic_id", widget: "string" }
      - { label: "Topic (full name)", name: "topic", widget: "string" }
  - name: "campus-partnerships-planning"
    label: "Campus Partnerships Planning"
    folder: "_campus-partnerships-planning"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Publishing Date", name: "date", widget: "datetime"}
      - {label: "Title", name: "title", widget: "string"}
      - {
          label: "Topic(s)",
          name: "article_topics",
          widget: "relation",
          collection: "topics",
          display_fields: [topic],
          search_fields: [topic],
          value_field: "topic_id",
        }
      - { label: "Article summary", name: "summary", widget: "text" }
      - {
          label: "Author",
          name: "author",
          widget: "relation",
          collection: "authors",
          display_fields: [display_name],
          search_fields: [display_name],
          value_field: "author_id",
        }
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "data-analysis"
    label: "Data Analysis"
    folder: "_data-analysis/"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Publishing Date", name: "date", widget: "datetime"}
      - {label: "Title", name: "title", widget: "string"}
      - {
          label: "Topic(s)",
          name: "article_topics",
          widget: "relation",
          collection: "topics",
          display_fields: [topic],
          search_fields: [topic],
          value_field: "topic_id",
        }
      - { label: "Article summary", name: "summary", widget: "text" }
      - {
          label: "Author",
          name: "author",
          widget: "relation",
          collection: "authors",
          display_fields: [display_name],
          search_fields: [display_name],
          value_field: "author_id",
        }
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "journal-cancellation-impact"
    label: "Journal Cancellation Impact"
    folder: "_journal-cancellation-impact/"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Publishing Date", name: "date", widget: "datetime"}
      - {label: "Title", name: "title", widget: "string"}
      - {
          label: "Topic(s)",
          name: "article_topics",
          widget: "relation",
          collection: "topics",
          display_fields: [topic],
          search_fields: [topic],
          value_field: "topic_id",
        }
      - { label: "Article summary", name: "summary", widget: "text" }
      - {
          label: "Author",
          name: "author",
          widget: "relation",
          collection: "authors",
          display_fields: [display_name],
          search_fields: [display_name],
          value_field: "author_id",
        }
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "reinvestments"
    label: "Reinvestments"
    folder: "_reinvestments/"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Publishing Date", name: "date", widget: "datetime"}
      - {label: "Title", name: "title", widget: "string"}
      - {
          label: "Topic(s)",
          name: "article_topics",
          widget: "relation",
          collection: "topics",
          display_fields: [topic],
          search_fields: [topic],
          value_field: "topic_id",
        }
      - { label: "Article summary", name: "summary", widget: "text" }
      - {
          label: "Author",
          name: "author",
          widget: "relation",
          collection: "authors",
          display_fields: [display_name],
          search_fields: [display_name],
          value_field: "author_id",
        }
      - {label: "Body", name: "body", widget: "markdown"}
