backend:
  name: git-gateway
  branch: master
  repo: sparcopen/negotiations
publish_mode: editorial_workflow
media_folder: "media/uploads"
collections:
  - name: "pages"
    label: "Landing pages"
    files:
      - label: "About"
        name: "about"
        file: "about.md"
        fields:
          - { label: "Title", name: "title", widget: "string", default: "About" }
          - { label: "Layout", name: "layout", widget: "hidden", default: "about" }
          - { label: "About summary", name: "summary", widget: "text" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Campus Partnerships Planning"
        name: "campus-partnerships-planning"
        file: "campus-partnerships-planning.md"
        fields:
          - { label: "Title", name: "title", widget: "string", default: "Campus Partnerships Planning" }
          - { label: "Layout", name: "layout", widget: "hidden", default: "thread" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Data Analysis"
        name: "data-analysis"
        file: "data-analysis.md"
        fields:
          - { label: "Title", name: "title", widget: "string", default: "Data Analysis" }
          - { label: "Layout", name: "layout", widget: "hidden", default: "thread" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Journal Cancellation Impact"
        name: "journal-cancellation-impact"
        file: "journal-cancellation-impact.md"
        fields:
          - { label: "Title", name: "title", widget: "string", default: "Journal Cancellation Impact" }
          - { label: "Layout", name: "layout", widget: "hidden", default: "thread" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Reinvestments"
        name: "reinvestments"
        file: "reinvestments.md"
        fields:
          - { label: "Title", name: "title", widget: "string", default: "Reinvestments" }
          - { label: "Layout", name: "layout", widget: "hidden", default: "thread" }
          - { label: "Body", name: "body", widget: "markdown" }
  - name: "authors"
    label: "Authors"
    label_singular: "Author"
    folder: "_authors/"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Display Name", name: "display_name", widget: "string" }
      - { label: "Affiliation", name: "affiliation", widget: "string", required: false }
      - { label: "Contact email", name: "email", widget: "string", required: false }
      - { label: "Link to external bio", name: "link_bio", widget: "string", required: false }
      - { label: "Short bio", name: "bio", widget: "text", required: false }
  - name: "topics"
    label: "Topics"
    label_singular: "Topic"
    folder: "_topics/"
    widget: "list"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Layout", name: "layout", default: "thread" }
      - { label: "Topic", name: "topic", widget: "string" }
  - name: "campus-partnerships-planning"
    label: "Campus Partnerships Planning"
    label_singular: "post"
    folder: "_campus-partnerships-planning"
    create: true
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Publishing Date", name: "date", widget: "datetime" }
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Topic(s)",
          name: "topics",
          widget: "relation",
          collection: "topics",
          multiple: true,
          display_fields: [topic],
          search_fields: [topic],
          value_field: "topic",
          required: false
        }
      - { label: "Article summary", name: "summary", widget: "text", required: false }
      - {
          label: "Author(s)",
          name: "authors",
          widget: "relation",
          collection: "authors",
          multiple: true,
          display_fields: [display_name],
          search_fields: [display_name],
          value_field: "display_name",
          required: false
        }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "data-analysis"
    label: "Data Analysis"
    label_singular: "post"
    folder: "_data-analysis/"
    create: true
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Publishing Date", name: "date", widget: "datetime" }
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Topic(s)",
          name: "topics",
          widget: "relation",
          collection: "topics",
          multiple: true,
          display_fields: [topic],
          search_fields: [topic],
          value_field: "topic",
          required: false
        }
      - { label: "Article summary", name: "summary", widget: "text", required: false }
      - {
          label: "Author(s)",
          name: "authors",
          widget: "relation",
          collection: "authors",
          multiple: true,
          display_fields: [display_name],
          search_fields: [display_name],
          value_field: "display_name",
          required: false
        }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "journal-cancellation-impact"
    label: "Journal Cancellation Impact"
    label_singular: "post"
    folder: "_journal-cancellation-impact/"
    create: true
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Publishing Date", name: "date", widget: "datetime" }
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Topic(s)",
          name: "topics",
          widget: "relation",
          collection: "topics",
          multiple: true,
          display_fields: [topic],
          search_fields: [topic],
          value_field: "topic",
          required: false
        }
      - { label: "Article summary", name: "summary", widget: "text", required: false }
      - {
          label: "Author(s)",
          name: "authors",
          widget: "relation",
          collection: "authors",
          multiple: true,
          display_fields: [display_name],
          search_fields: [display_name],
          value_field: "display_name",
          required: false
        }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "reinvestments"
    label: "Reinvestments"
    label_singular: "post"
    folder: "_reinvestments/"
    create: true
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Publishing Date", name: "date", widget: "datetime" }
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Topic(s)",
          name: "topics",
          widget: "relation",
          collection: "topics",
          multiple: true,
          display_fields: [topic],
          search_fields: [topic],
          value_field: "topic",
          required: false
        }
      - { label: "Article summary", name: "summary", widget: "text", required: false }
      - {
          label: "Author(s)",
          name: "authors",
          widget: "relation",
          collection: "authors",
          multiple: true,
          display_fields: [display_name],
          search_fields: [display_name],
          value_field: "display_name",
          required: false
        }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "blog"
    label: "Blog"
    folder: "_blog/"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Publishing Date", name: "date", widget: "datetime" }
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Topic(s)",
          name: "article_topics",
          widget: "relation",
          collection: "topics",
          display_fields: [topic],
          search_fields: [topic],
          value_field: "topic_id",
          required: false
        }
      - { label: "Body", name: "body", widget: "markdown" }
